name: Java CI

on: [push, release]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload to release
      if: github.event == 'release'
      uses: JasonEtco/upload-to-release@master
      with:
        args: target/disc0rd-exe.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
